//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrankensteinWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public Appointment()
        {
            this.AppointmentDetails = new HashSet<AppointmentDetail>();
            this.MedicalTests = new HashSet<MedicalTest>();
            this.Treatments = new HashSet<Treatment>();
        }
    
        public int AppointmentId { get; set; }
        public int PersonId { get; set; }
        public int DoctorId { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public int StatusId { get; set; }
    
        public virtual ICollection<AppointmentDetail> AppointmentDetails { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<MedicalTest> MedicalTests { get; set; }
        public virtual ICollection<Treatment> Treatments { get; set; }
    }
}
