//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrankensteinWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicLocation
    {
        public ClinicLocation()
        {
            this.Doctors = new HashSet<Doctor>();
        }
    
        public int LocationId { get; set; }
        public string ClinicName { get; set; }
        public string ClinicAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string Details { get; set; }
    
        public virtual ICollection<Doctor> Doctors { get; set; }
    }
}
