//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrankensteinWS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FrankensteinEntities : DbContext
    {
        public FrankensteinEntities()
            : base("name=FrankensteinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Doctor> Doctors { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Visit> Visits { get; set; }
    
        public virtual ObjectResult<GetUsersTest_Result> GetUsersTest(Nullable<int> p_ID_USER)
        {
            var p_ID_USERParameter = p_ID_USER.HasValue ?
                new ObjectParameter("p_ID_USER", p_ID_USER) :
                new ObjectParameter("p_ID_USER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsersTest_Result>("GetUsersTest", p_ID_USERParameter);
        }
    }
}
