//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrankensteinWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.MedicalTests = new HashSet<MedicalTest>();
        }
    
        public int TestId { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> MinValue { get; set; }
        public Nullable<decimal> MaxValue { get; set; }
        public string UnitMeasure { get; set; }
    
        public virtual ICollection<MedicalTest> MedicalTests { get; set; }
    }
}
