//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrankensteinWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentDetail
    {
        public int TreatmentDetailId { get; set; }
        public int TreatmentId { get; set; }
        public int DrugId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Tablets { get; set; }
        public Nullable<int> Dose { get; set; }
        public Nullable<bool> PeriodicityType { get; set; }
        public Nullable<int> Periodicity { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
