//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrankensteinWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Visits = new HashSet<Visit>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
